### ISSUE TITLE
The .desktop file doesn't work for non-Elronnd people

### ISSUE THREAD

**Issue by dhouck** [Elronnd/mafia-auto-updater#5]
I prefer to have my KoLMafia installation under my own home directory, not in `/home/elronnd/bin/mafia`. I also don't want to put it in `~/bin/mafia`, but that would be better than in your home directory (especially since you don't have an account on my computer). Could the makefile `sed` in a more appropriate variable, defaulting to `${HOME}/bin/mafia` but allowing a different option?

**Comment by Elronnd** [comment]
Fixed!  Also, TIL anyone uses this awful mess of a script

**Comment by Elronnd** [comment]
Also I think this is one of the greatest oversights I've ever made:

* Desktop script refers to *my* home directory

* Even though I've never used the desktop script

* ...and the makefile doesn't even install to *anyone*'s home directory
